/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvisoryApplication {
  'id' : bigint,
  'status' : string,
  'estimatedBudgetRange' : string,
  'workEmail' : string,
  'currentSecuritySetup' : string,
  'source' : string,
  'fullName' : string,
  'submittedAt' : Time,
  'companyName' : string,
  'companySize' : string,
  'companyWebsite' : string,
  'fundingStage' : string,
  'primaryConcern' : string,
  'industry' : string,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishDate' : Time,
  'featuredImage' : string,
  'tags' : Array<string>,
  'author' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface LeadExport {
  'source' : string,
  'name' : string,
  'tags' : Array<string>,
  'email' : string,
  'timestamp' : Time,
}
export interface LeadTag {
  'source' : string,
  'tags' : Array<string>,
  'category' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLeadTag' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'analyticsAccessInstructions' : ActorMethod<[], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, Array<string>, string],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'exportLeadsAsJSON' : ActorMethod<[], Array<LeadExport>>,
  'getAllAdvisoryApplications' : ActorMethod<[], Array<AdvisoryApplication>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllLeadTags' : ActorMethod<[], Array<LeadTag>>,
  'getBlogPostsByTag' : ActorMethod<[string], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeadTags' : ActorMethod<[string], [] | [LeadTag]>,
  'getRecentInboundWebhooks' : ActorMethod<[string], Array<string>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'queryLeadDataWithToken' : ActorMethod<
    [string, string, string],
    [] | [LeadExport]
  >,
  'recordLeadDownload' : ActorMethod<[string, string, string], undefined>,
  'recordOrder' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    bigint
  >,
  'registerToken' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitAdvisoryApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdvisoryApplicationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, Array<string>, string],
    undefined
  >,
  'updateContactSubmissionStatus' : ActorMethod<[bigint, string], undefined>,
  'updateDownloadStatus' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOrderTags' : ActorMethod<[bigint, Array<string>], undefined>,
  'verifyToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];